const cfg=window.ZING_CONFIG;const $=s=>document.querySelector(s),id=s=>document.getElementById(s);
const gate=document.createElement('section');gate.id='zing-login';gate.innerHTML='<form><h2>Bienvenue sur Zing</h2><p>Connecte-toi pour retrouver tes amis.</p><input name="email" type="email" placeholder="E-mail" required><input name="password" type="password" placeholder="Mot de passe (8 caractères minimum)" minlength="8" required><input name="username" placeholder="Nom d’utilisateur (pour créer un compte)" hidden><button>Se connecter</button><a href="#">Créer un compte</a><small></small></form>';document.body.append(gate);const style=document.createElement('style');style.textContent='#zing-login{position:fixed;z-index:99;inset:0;background:#e9eddf;display:grid;place-items:center;font:14px Arial}#zing-login form{background:white;padding:28px;border-radius:20px;width:min(340px,85vw);display:grid;gap:12px;box-shadow:0 15px 50px #0002}#zing-login input,#zing-login button{padding:12px;border:1px solid #ddd;border-radius:10px}#zing-login button{background:#222;color:white}#zing-login a{color:#546a29}';document.head.append(style);
const form=gate.querySelector('form'),link=gate.querySelector('a'),note=gate.querySelector('small'),userField=form.username;let signup=false,db=cfg&&window.supabase?window.supabase.createClient(cfg.url,cfg.key):null,me=null,chat=null;
link.onclick=e=>{e.preventDefault();signup=!signup;userField.hidden=!signup;userField.required=signup;form.querySelector('button').textContent=signup?'Créer mon compte':'Se connecter';link.textContent=signup?'J’ai déjà un compte':'Créer un compte'};
function toast(t){const x=id('toast');if(x){x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}else note.textContent=t}
function showApp(){gate.remove();const out=document.createElement('button');out.textContent='Déconnexion';out.onclick=()=>db.auth.signOut();$('.top-actions')?.append(out)}
if(!db){note.textContent='Connexion indisponible pour le moment.'}else{db.auth.getSession().then(({data})=>{if(data.session){me=data.session.user;showApp()}});db.auth.onAuthStateChange((ev,s)=>{if(s){me=s.user;showApp()}})}
form.onsubmit=async e=>{e.preventDefault();if(!db)return;const email=form.email.value.trim(),password=form.password.value;let r=signup?await db.auth.signUp({email,password,options:{data:{username:userField.value.trim().toLowerCase()}}}):await db.auth.signInWithPassword({email,password});if(r.error){note.textContent=r.error.message;return}if(signup&&!r.data.session){note.textContent='Compte créé : confirme ton e-mail.';return}me=r.data.user;showApp()};
const newBtn=id('new-message');newBtn?.addEventListener('click',async e=>{e.stopImmediatePropagation();if(!me)return toast('Connecte-toi d’abord.');const name=prompt('Nom d’utilisateur de ton ami ?');if(!name)return;const p=await db.from('profiles').select('id').eq('username',name.replace('@','').toLowerCase()).maybeSingle();if(!p.data)return toast('Membre introuvable.');const c=await db.rpc('create_zing_direct_conversation',{target_user_id:p.data.id});if(c.error)return toast(c.error.message);toast('Conversation créée.');});
